source 'http://git.sdos.es/ios/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_modular_headers!
inhibit_all_warnings!

def shared_pods
    pod 'SDOS/Default'
	pod 'SDOSKeyedCodable', :path => '../../'
end

target :SDOSKeyedCodable_Example do
	shared_pods
end