source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_modular_headers!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSKeyedCodable', :path => '../../'
end

target :SDOSKeyedCodableSample do
	shared_pods
end
